PRAGMA foreign_keys=ON;
CREATE TABLE IF NOT EXISTS schema_versions(version INTEGER PRIMARY KEY, applied_at TEXT NOT NULL);
CREATE TABLE organizations(id TEXT PRIMARY KEY,name TEXT NOT NULL,synthetic INTEGER NOT NULL DEFAULT 1);
CREATE TABLE users(id TEXT PRIMARY KEY,organization_id TEXT NOT NULL REFERENCES organizations(id),name TEXT NOT NULL,email TEXT UNIQUE NOT NULL,password_hash TEXT NOT NULL,role TEXT NOT NULL,created_at TEXT NOT NULL);
CREATE TABLE sessions(token_hash TEXT PRIMARY KEY,user_id TEXT REFERENCES users(id),csrf TEXT NOT NULL,expires_at REAL NOT NULL);
CREATE TABLE properties(id TEXT PRIMARY KEY,organization_id TEXT NOT NULL REFERENCES organizations(id),created_by TEXT REFERENCES users(id),address TEXT NOT NULL,city TEXT NOT NULL,property_type TEXT NOT NULL,units INTEGER NOT NULL,asking_price REAL,description TEXT NOT NULL,state TEXT NOT NULL DEFAULT 'DRAFT',synthetic INTEGER NOT NULL DEFAULT 1,version INTEGER NOT NULL DEFAULT 1,created_at TEXT NOT NULL);
CREATE TABLE artifacts(id TEXT PRIMARY KEY,property_id TEXT NOT NULL REFERENCES properties(id),contributor TEXT NOT NULL REFERENCES users(id),filename TEXT NOT NULL,sha256 TEXT NOT NULL,content TEXT NOT NULL,state TEXT NOT NULL,security_findings TEXT NOT NULL,version INTEGER NOT NULL,created_at TEXT NOT NULL);
CREATE TABLE claims(id TEXT PRIMARY KEY,property_id TEXT NOT NULL REFERENCES properties(id),artifact_id TEXT REFERENCES artifacts(id),field TEXT NOT NULL,value_json TEXT NOT NULL,category TEXT NOT NULL,contributor TEXT REFERENCES users(id),source_reference TEXT NOT NULL,version INTEGER NOT NULL,created_at TEXT NOT NULL);
CREATE TABLE claim_confirmations(id TEXT PRIMARY KEY,claim_id TEXT NOT NULL REFERENCES claims(id),actor_id TEXT NOT NULL REFERENCES users(id),created_at TEXT NOT NULL,UNIQUE(claim_id,actor_id));
CREATE TABLE professional_opinions(id TEXT PRIMARY KEY,property_id TEXT REFERENCES properties(id),artifact_id TEXT REFERENCES artifacts(id),author TEXT NOT NULL,credentials TEXT NOT NULL,opinion_json TEXT NOT NULL,created_at TEXT NOT NULL);
CREATE TABLE model_estimates(id TEXT PRIMARY KEY,property_id TEXT REFERENCES properties(id),model_version TEXT NOT NULL,inputs_json TEXT NOT NULL,result_json TEXT NOT NULL,created_at TEXT NOT NULL);
CREATE TABLE underwriting_snapshots(id TEXT PRIMARY KEY,property_id TEXT REFERENCES properties(id),creator TEXT REFERENCES users(id),input_values TEXT NOT NULL,evidence_refs TEXT NOT NULL,formula_version TEXT NOT NULL,assumptions TEXT NOT NULL,scenarios TEXT NOT NULL,results TEXT NOT NULL,review_state TEXT NOT NULL,created_at TEXT NOT NULL);
CREATE TABLE derived_metrics(id TEXT PRIMARY KEY,snapshot_id TEXT REFERENCES underwriting_snapshots(id),name TEXT NOT NULL,value_json TEXT NOT NULL,formula_version TEXT NOT NULL);
CREATE TABLE evidence_requests(id TEXT PRIMARY KEY,property_id TEXT REFERENCES properties(id),field TEXT NOT NULL,reason TEXT NOT NULL,actor_id TEXT REFERENCES users(id),created_at TEXT NOT NULL);
CREATE TABLE asset_claims(id TEXT PRIMARY KEY,property_id TEXT REFERENCES properties(id),kind TEXT NOT NULL,label TEXT NOT NULL,amount REAL,status TEXT NOT NULL DEFAULT 'UNVERIFIED',source_claim_id TEXT REFERENCES claims(id),created_by TEXT REFERENCES users(id),created_at TEXT NOT NULL);
CREATE TABLE legal_entities(id TEXT PRIMARY KEY,name TEXT NOT NULL,kind TEXT NOT NULL,scope TEXT NOT NULL,synthetic INTEGER NOT NULL DEFAULT 1);
CREATE TABLE deals(id TEXT PRIMARY KEY,property_id TEXT NOT NULL REFERENCES properties(id),legal_entity_id TEXT REFERENCES legal_entities(id),state TEXT NOT NULL,kind TEXT NOT NULL,created_at TEXT NOT NULL);
CREATE TABLE capital_requirements(id TEXT PRIMARY KEY,deal_id TEXT REFERENCES deals(id),amount_cents INTEGER NOT NULL,currency TEXT NOT NULL,purpose TEXT NOT NULL);
CREATE TABLE instruments(id TEXT PRIMARY KEY,legal_entity_id TEXT REFERENCES legal_entities(id),kind TEXT NOT NULL,scope TEXT NOT NULL,transfer_policy TEXT NOT NULL);
CREATE TABLE offerings(id TEXT PRIMARY KEY,deal_id TEXT NOT NULL REFERENCES deals(id),instrument_id TEXT REFERENCES instruments(id),state TEXT NOT NULL,target_cents INTEGER NOT NULL,min_cents INTEGER NOT NULL,fee_bps INTEGER NOT NULL,created_at TEXT NOT NULL);
CREATE TABLE eligibility(user_id TEXT PRIMARY KEY REFERENCES users(id),state TEXT NOT NULL,reviewed_by TEXT REFERENCES users(id),reviewed_at TEXT NOT NULL,simulation INTEGER NOT NULL DEFAULT 1);
CREATE TABLE room_grants(user_id TEXT REFERENCES users(id),property_id TEXT REFERENCES properties(id),level INTEGER NOT NULL,granted_by TEXT REFERENCES users(id),created_at TEXT NOT NULL,PRIMARY KEY(user_id,property_id));
CREATE TABLE holdings(id TEXT PRIMARY KEY,user_id TEXT REFERENCES users(id),offering_id TEXT REFERENCES offerings(id),principal_cents INTEGER NOT NULL,fee_cents INTEGER NOT NULL,state TEXT NOT NULL,created_at TEXT NOT NULL);
CREATE TABLE transactions(id TEXT PRIMARY KEY,user_id TEXT REFERENCES users(id),offering_id TEXT REFERENCES offerings(id),kind TEXT NOT NULL,amount_cents INTEGER NOT NULL,state TEXT NOT NULL,idempotency_key TEXT UNIQUE NOT NULL,created_at TEXT NOT NULL);
CREATE TABLE distributions(id TEXT PRIMARY KEY,transaction_id TEXT REFERENCES transactions(id),holding_id TEXT REFERENCES holdings(id),amount_cents INTEGER NOT NULL,created_at TEXT NOT NULL);
CREATE TABLE action_proposals(id TEXT PRIMARY KEY,actor_id TEXT REFERENCES users(id),action TEXT NOT NULL,resource_id TEXT NOT NULL,payload TEXT NOT NULL,decision TEXT NOT NULL,policy TEXT NOT NULL,reason TEXT NOT NULL,created_at TEXT NOT NULL);
CREATE TABLE agent_runs(id TEXT PRIMARY KEY,property_id TEXT REFERENCES properties(id),agent_id TEXT NOT NULL,envelope TEXT NOT NULL,created_at TEXT NOT NULL);
CREATE TABLE audit_events(seq INTEGER PRIMARY KEY AUTOINCREMENT,id TEXT UNIQUE NOT NULL,actor_id TEXT NOT NULL,organization_id TEXT,resource_id TEXT NOT NULL,event TEXT NOT NULL,details TEXT NOT NULL,previous_hash TEXT NOT NULL,event_hash TEXT NOT NULL,created_at TEXT NOT NULL);
CREATE INDEX property_tenant ON properties(organization_id);
CREATE INDEX claim_property ON claims(property_id);
CREATE INDEX audit_resource ON audit_events(resource_id);
CREATE TRIGGER artifacts_no_update BEFORE UPDATE ON artifacts BEGIN SELECT RAISE(ABORT,'Immutable evidence'); END;
CREATE TRIGGER artifacts_no_delete BEFORE DELETE ON artifacts BEGIN SELECT RAISE(ABORT,'Immutable evidence'); END;
CREATE TRIGGER claims_no_update BEFORE UPDATE ON claims BEGIN SELECT RAISE(ABORT,'Immutable claims'); END;
CREATE TRIGGER claims_no_delete BEFORE DELETE ON claims BEGIN SELECT RAISE(ABORT,'Immutable claims'); END;
CREATE TRIGGER snapshots_no_update BEFORE UPDATE ON underwriting_snapshots BEGIN SELECT RAISE(ABORT,'Immutable underwriting'); END;
CREATE TRIGGER snapshots_no_delete BEFORE DELETE ON underwriting_snapshots BEGIN SELECT RAISE(ABORT,'Immutable underwriting'); END;
CREATE TRIGGER audit_no_update BEFORE UPDATE ON audit_events BEGIN SELECT RAISE(ABORT,'Append-only audit'); END;
CREATE TRIGGER audit_no_delete BEFORE DELETE ON audit_events BEGIN SELECT RAISE(ABORT,'Append-only audit'); END;
